id: P002917
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN556
  title: སྡོམ་གསུམ་རྩ་འགྲེལ། ལྷུང་བཤགས་དང་སྨོན་ལམ་རྣམ་ལྔའི་འགྲེལ་པ།
  author: ''
  volumes:
    b661ba5fb61f4e888cc9685468066323:
      image_group_id: I3CN3981
      title: ''
      volume_number: 1
      total_pages: 296
